from .carro import Carro
from .cliente import Cliente
from .reserva import Reserva
from .funcionario import Funcionario
from .loja import Loja
from .modelo import Modelo
from .pagamento import Pagamento
from .patio import Patio
from .manobrista import Manobrista